# demo
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    - repoURL: https://github.com/encore-tvm/argocd-demo.git
      targetRevision: HEAD
      path: prd

  destination: 
    server: https://kubernetes.default.svc
    namespace: ns1

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
